from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base, JSONBType, MetadataMixin, OrgMixin, TimestampMixin, UUIDMixin, UUIDType


class GeneratedCreative(Base, UUIDMixin, OrgMixin, TimestampMixin, MetadataMixin):
    """Image generated by a provider (mock Pillow or OpenAI)."""

    __tablename__ = "generated_creatives"

    prompt_version_id: Mapped[uuid.UUID] = mapped_column(
        UUIDType, ForeignKey("prompt_versions.id"), nullable=False, index=True
    )
    provider: Mapped[str] = mapped_column(String(50), nullable=False)  # mock | openai
    model_used: Mapped[str | None] = mapped_column(String(100), nullable=True)
    parameters: Mapped[dict[str, Any] | None] = mapped_column(JSONBType, nullable=True)

    file_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    file_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    width: Mapped[int | None] = mapped_column(Integer, nullable=True)
    height: Mapped[int | None] = mapped_column(Integer, nullable=True)
    file_size_bytes: Mapped[int | None] = mapped_column(Integer, nullable=True)
    mime_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    estimated_cost_usd: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Phase 4 — storage abstraction
    storage_key: Mapped[str | None] = mapped_column(Text, nullable=True)
    storage_backend: Mapped[str | None] = mapped_column(String(20), nullable=True)
    # Perceptual hash for near-duplicate detection
    phash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    # Denormalized link to originating source ad (for approval panel)
    source_ad_id: Mapped[uuid.UUID | None] = mapped_column(UUIDType, nullable=True, index=True)
    # Self-reference: new variation created from a rejected creative
    variation_of_id: Mapped[uuid.UUID | None] = mapped_column(UUIDType, nullable=True)

    status: Mapped[str] = mapped_column(
        String(50), default="awaiting_approval", nullable=False
    )
    # Valid statuses: queued | generating | generated | checking |
    #                 blocked | awaiting_approval | approved | rejected | failed
    is_fictitious: Mapped[bool] = mapped_column(default=False, nullable=False)

    prompt_version: Mapped[PromptVersion] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "PromptVersion", back_populates="generated_creatives"
    )
    quality_checks: Mapped[list[QualityCheck]] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "QualityCheck", back_populates="creative"
    )
    policy_checks: Mapped[list[PolicyCheck]] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "PolicyCheck", back_populates="creative"
    )
    approvals: Mapped[list[Approval]] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "Approval", back_populates="creative"
    )
    published_ads: Mapped[list[PublishedAd]] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "PublishedAd", back_populates="creative"
    )
    assets: Mapped[list[CreativeAsset]] = relationship(  # type: ignore[name-defined]  # noqa: F821
        "CreativeAsset", back_populates="creative"
    )
