"""
Asset serving — GET /assets/{token}

Validates the HMAC signed token generated by LocalStorage.signed_url() and
streams the file. No auth cookie required — the HMAC token itself provides
access control + expiry.

For S3 backends, signed_url() returns a direct presigned S3 URL that the
client accesses without going through this endpoint.
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

router = APIRouter()


@router.get("/{token}")
async def serve_asset(token: str) -> FileResponse:
    from app.config import get_settings

    settings = get_settings()
    from packages.storage.local import LocalStorage

    ls = LocalStorage(base_dir=settings.storage_local_dir, secret_key=settings.secret_key)

    try:
        claims = ls.verify_token(token)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=f"Asset not found: {exc}") from exc

    from pathlib import Path

    raw = ls.local_path(claims["org_id"], claims["key"])
    path = Path(raw) if raw else None
    if not path or not path.exists():
        raise HTTPException(status_code=404, detail="File not found in storage")

    # Infer content type from extension
    suffix = path.suffix.lower()
    media_type = {
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
    }.get(suffix, "application/octet-stream")

    return FileResponse(str(path), media_type=media_type)
