"""phase1_initial

Revision ID: 3e52a51ad4ff
Revises:
Create Date: 2026-06-10 12:59:55.682191

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db


revision: str = '3e52a51ad4ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=200), nullable=True),
    sa.Column('payload', app.db.JSONBType(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_table('experiments',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('primary_variable', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('min_spend', sa.Float(), nullable=True),
    sa.Column('min_impressions', sa.Integer(), nullable=True),
    sa.Column('min_days', sa.Integer(), nullable=True),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_organization_id'), 'experiments', ['organization_id'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_verified_at', sa.String(length=50), nullable=True),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_credentials_organization_id'), 'integration_credentials', ['organization_id'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_table('brand_profiles',
    sa.Column('product_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=True),
    sa.Column('secondary_color', sa.String(length=20), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('logo_guidelines', sa.Text(), nullable=True),
    sa.Column('tone_of_voice', sa.Text(), nullable=True),
    sa.Column('prohibited_elements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_profiles_organization_id'), 'brand_profiles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_brand_profiles_product_id'), 'brand_profiles', ['product_id'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('product_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('ad_format', sa.String(length=50), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_organization_id'), 'prompt_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_product_id'), 'prompt_templates', ['product_id'], unique=False)
    op.create_table('source_ads',
    sa.Column('product_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('cta', sa.String(length=100), nullable=True),
    sa.Column('landing_page_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('ad_format', sa.String(length=50), nullable=True),
    sa.Column('placement', sa.String(length=100), nullable=True),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('performance_label', sa.String(length=20), nullable=True),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_ads_external_id'), 'source_ads', ['external_id'], unique=False)
    op.create_index(op.f('ix_source_ads_organization_id'), 'source_ads', ['organization_id'], unique=False)
    op.create_index(op.f('ix_source_ads_product_id'), 'source_ads', ['product_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('brand_assets',
    sa.Column('brand_profile_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_assets_brand_profile_id'), 'brand_assets', ['brand_profile_id'], unique=False)
    op.create_index(op.f('ix_brand_assets_organization_id'), 'brand_assets', ['organization_id'], unique=False)
    op.create_table('creative_analyses',
    sa.Column('source_ad_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('visual_summary', sa.String(length=2000), nullable=True),
    sa.Column('composition', app.db.JSONBType(), nullable=True),
    sa.Column('hierarchy', app.db.JSONBType(), nullable=True),
    sa.Column('product_presentation', app.db.JSONBType(), nullable=True),
    sa.Column('color_and_lighting', app.db.JSONBType(), nullable=True),
    sa.Column('text_analysis', app.db.JSONBType(), nullable=True),
    sa.Column('attention_elements', app.db.JSONBType(), nullable=True),
    sa.Column('strengths', app.db.JSONBType(), nullable=True),
    sa.Column('weaknesses', app.db.JSONBType(), nullable=True),
    sa.Column('performance_hypotheses', app.db.JSONBType(), nullable=True),
    sa.Column('elements_to_preserve', app.db.JSONBType(), nullable=True),
    sa.Column('elements_to_test', app.db.JSONBType(), nullable=True),
    sa.Column('policy_risks', app.db.JSONBType(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['source_ad_id'], ['source_ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creative_analyses_organization_id'), 'creative_analyses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_creative_analyses_source_ad_id'), 'creative_analyses', ['source_ad_id'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('source_ad_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('date_start', sa.String(length=20), nullable=True),
    sa.Column('date_stop', sa.String(length=20), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Float(), nullable=True),
    sa.Column('spend', sa.Float(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('link_clicks', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('cpc', sa.Float(), nullable=True),
    sa.Column('cpm', sa.Float(), nullable=True),
    sa.Column('landing_page_views', sa.Integer(), nullable=True),
    sa.Column('adds_to_cart', sa.Integer(), nullable=True),
    sa.Column('initiate_checkout', sa.Integer(), nullable=True),
    sa.Column('purchases', sa.Integer(), nullable=True),
    sa.Column('leads', sa.Integer(), nullable=True),
    sa.Column('cost_per_result', sa.Float(), nullable=True),
    sa.Column('purchase_value', sa.Float(), nullable=True),
    sa.Column('roas', sa.Float(), nullable=True),
    sa.Column('raw_response', app.db.JSONBType(), nullable=True),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['source_ad_id'], ['source_ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_organization_id'), 'performance_snapshots', ['organization_id'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_source_ad_id'), 'performance_snapshots', ['source_ad_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('template_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('source_ad_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('analysis_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('parent_version_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('structured_fields', app.db.JSONBType(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('learning_used', sa.Text(), nullable=True),
    sa.Column('author_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('parameters', app.db.JSONBType(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['creative_analyses.id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['prompt_versions.id'], ),
    sa.ForeignKeyConstraint(['source_ad_id'], ['source_ads.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_analysis_id'), 'prompt_versions', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_organization_id'), 'prompt_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_source_ad_id'), 'prompt_versions', ['source_ad_id'], unique=False)
    op.create_index(op.f('ix_prompt_versions_template_id'), 'prompt_versions', ['template_id'], unique=False)
    op.create_table('generated_creatives',
    sa.Column('prompt_version_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('parameters', app.db.JSONBType(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_creatives_file_hash'), 'generated_creatives', ['file_hash'], unique=False)
    op.create_index(op.f('ix_generated_creatives_organization_id'), 'generated_creatives', ['organization_id'], unique=False)
    op.create_index(op.f('ix_generated_creatives_prompt_version_id'), 'generated_creatives', ['prompt_version_id'], unique=False)
    op.create_table('approvals',
    sa.Column('creative_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('decided_by', app.db.UUIDType(length=36), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('snapshot_prompt', sa.Text(), nullable=True),
    sa.Column('snapshot_copy', sa.Text(), nullable=True),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['generated_creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_creative_id'), 'approvals', ['creative_id'], unique=False)
    op.create_index(op.f('ix_approvals_organization_id'), 'approvals', ['organization_id'], unique=False)
    op.create_table('experiment_variants',
    sa.Column('experiment_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('creative_id', app.db.UUIDType(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_fictitious', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['generated_creatives.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_variants_experiment_id'), 'experiment_variants', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_experiment_variants_organization_id'), 'experiment_variants', ['organization_id'], unique=False)
    op.create_table('policy_checks',
    sa.Column('creative_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('findings', app.db.JSONBType(), nullable=True),
    sa.Column('rule_set_version', sa.String(length=50), nullable=True),
    sa.Column('override_by', app.db.UUIDType(length=36), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['generated_creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_checks_creative_id'), 'policy_checks', ['creative_id'], unique=False)
    op.create_index(op.f('ix_policy_checks_organization_id'), 'policy_checks', ['organization_id'], unique=False)
    op.create_table('published_ads',
    sa.Column('creative_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('payload', app.db.JSONBType(), nullable=True),
    sa.Column('meta_campaign_id', sa.String(length=200), nullable=True),
    sa.Column('meta_adset_id', sa.String(length=200), nullable=True),
    sa.Column('meta_ad_id', sa.String(length=200), nullable=True),
    sa.Column('meta_creative_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['generated_creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_ads_creative_id'), 'published_ads', ['creative_id'], unique=False)
    op.create_index(op.f('ix_published_ads_idempotency_key'), 'published_ads', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_published_ads_organization_id'), 'published_ads', ['organization_id'], unique=False)
    op.create_table('quality_checks',
    sa.Column('creative_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('findings', app.db.JSONBType(), nullable=True),
    sa.Column('override_by', app.db.UUIDType(length=36), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('organization_id', app.db.UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata', app.db.JSONBType(), nullable=True),
    sa.ForeignKeyConstraint(['creative_id'], ['generated_creatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_checks_creative_id'), 'quality_checks', ['creative_id'], unique=False)
    op.create_index(op.f('ix_quality_checks_organization_id'), 'quality_checks', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_checks_organization_id'), table_name='quality_checks')
    op.drop_index(op.f('ix_quality_checks_creative_id'), table_name='quality_checks')
    op.drop_table('quality_checks')
    op.drop_index(op.f('ix_published_ads_organization_id'), table_name='published_ads')
    op.drop_index(op.f('ix_published_ads_idempotency_key'), table_name='published_ads')
    op.drop_index(op.f('ix_published_ads_creative_id'), table_name='published_ads')
    op.drop_table('published_ads')
    op.drop_index(op.f('ix_policy_checks_organization_id'), table_name='policy_checks')
    op.drop_index(op.f('ix_policy_checks_creative_id'), table_name='policy_checks')
    op.drop_table('policy_checks')
    op.drop_index(op.f('ix_experiment_variants_organization_id'), table_name='experiment_variants')
    op.drop_index(op.f('ix_experiment_variants_experiment_id'), table_name='experiment_variants')
    op.drop_table('experiment_variants')
    op.drop_index(op.f('ix_approvals_organization_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_creative_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_generated_creatives_prompt_version_id'), table_name='generated_creatives')
    op.drop_index(op.f('ix_generated_creatives_organization_id'), table_name='generated_creatives')
    op.drop_index(op.f('ix_generated_creatives_file_hash'), table_name='generated_creatives')
    op.drop_table('generated_creatives')
    op.drop_index(op.f('ix_prompt_versions_template_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_source_ad_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_organization_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_analysis_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_performance_snapshots_source_ad_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_organization_id'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_creative_analyses_source_ad_id'), table_name='creative_analyses')
    op.drop_index(op.f('ix_creative_analyses_organization_id'), table_name='creative_analyses')
    op.drop_table('creative_analyses')
    op.drop_index(op.f('ix_brand_assets_organization_id'), table_name='brand_assets')
    op.drop_index(op.f('ix_brand_assets_brand_profile_id'), table_name='brand_assets')
    op.drop_table('brand_assets')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_ads_product_id'), table_name='source_ads')
    op.drop_index(op.f('ix_source_ads_organization_id'), table_name='source_ads')
    op.drop_index(op.f('ix_source_ads_external_id'), table_name='source_ads')
    op.drop_table('source_ads')
    op.drop_index(op.f('ix_prompt_templates_product_id'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_organization_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_brand_profiles_product_id'), table_name='brand_profiles')
    op.drop_index(op.f('ix_brand_profiles_organization_id'), table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_integration_credentials_organization_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_experiments_organization_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
